apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  description: >-
    This Task is Golang task to build Go projects.
    params:
    - name: username
      value: $(params.username)  
  params:
  - name: username
  steps:
  - image: alpine:3.15
    script: |
      echo "hello $(params.username)"
