apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  description: >-
    This Task is used to echo name.
  params:
  - name: username
    value: $(params.username)  
  steps:
  - image: alpine:3.15
    script: |
      echo "hello $(params.username)"
